### ISSUE TITLE
[BUG] Job replication failed with S3 backend

### ISSUE THREAD

**Issue by yancl** [vmware/harbor#1006]
Hi, 

  Recently we found that job replication with s3 pre-sign url does not work, after some dig, we found that the
**Headers** of request to S3 has the **OAuth** token with the key of *Authorization*, that is not allowed by S3 service. so will you please remove the **OAuth**  key from request headers? thanks.

Below are the request process:
```
1.307 | GET http://registry:5000/xxx/blobs/sha256:xxxxxxxx
2.400 | GET http://xxxx.amazonaws.com.cn/xxxx/sha256/xxxx/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxx
Host: xxxx.amazonaws.com.cn
User-Agent: harbor-registry-client
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx
```

as you can see above, it has extra `Authorization: Bearer xx` in the headers which should not belong the request to S3, and that cause S3 service refuse the normal request.

**Comment by reasonerjt** [comment]
Hi, thanks for reporting this, did you deploy Harbor with S3 as a storage backend?
as for the second request, is it sent by docker client?  Sorry I'm not quite sure how S3 driver of registry works, but if this is the case this seems an issue with cooperation between docker client and S3 driver.

**Comment by yancl** [comment]
@reasonerjt yes, we config the storage of registry to be the S3, but according the logs, it seems that the job replication matters.

the debug logs are as follow:
```
jobservice[14304]: 2016-11-02T13:26:49Z [DEBUG] [transport.go:51]: 400 | GET http://xxxx.amazonaws.com.cn/xxxx/sha256/xxxx/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxx
Host: xxxx.amazonaws.com.cn
User-Agent: harbor-registry-client
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx
```

as you can see, it is the harbor jobservice make the request, not through the docker engine, and  the `User-Agent: harbor-registry-client` also prove it.

I think the replication process(`Registry-A-->Registry-B`) is like this?
`Registry-A-->Jobservice-A--->fetch layers of image from local docker registry--->send layers of image to Registry-B`

And the problem occurs at JobserviceA fetching layers,  since there is `Authorization: Bearer` in the headers, which means `OAuth` authentication, so maybe the harbor code has some state not cleared during job replication?

**Comment by reasonerjt** [comment]
Good point, sorry I misunderstood, we'll look into that.

**Comment by yancl** [comment]
thanks :)

**Comment by ywk253100** [comment]
Fixed by #1224 .

**Comment by yancl** [comment]
@ywk253100 the problem still exists, will you please reopen the issue?

I pull the 0.5 release code and merge the diff and build the offline package, but when test with S3 there is still
`Authorization: Bearer` in the request header which cause S3 api call failed.

**Comment by ywk253100** [comment]
The fix is merged into dev branch, you can use the dev code to test it.

**Comment by yancl** [comment]
ok, i will have a test. thanks.

**Comment by yancl** [comment]
@ywk253100  it works as expect, thank you very much!!!

**Comment by yancl** [comment]
the reason is that i use docker-compose up/down manually and forgot to load the packed image.
I should have used install.sh:)
