### ISSUE TITLE
Harbor OVA does not reconfigure the network settings in subsequent boot when it fails in the firstboot

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#1104]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 

Steps:
1. Deploy Harbor OVA on a ESX host with wrong/incorrect network port-group (VM Network) chosen (accidentally) which does not have DHCP capability 
2. Harbor OVA firstboot fails with "Failed to get the IP address"
3. User corrects the networking issue in the VM (configures vm virtual nic/Network adapter) it back to the right network which has DHCP capability 
4. User corrects the VM networking (restarts systemd-networkd) and DHCP-IP and sets the hostname
5. Reboot the Harbor OVA
6. Subsequent boot fails - Expectation is subsequent boot could recover the system?

This is a nice to have feature. Feel free to push to next release..
> firstboot.log : 
```
Loaded image: vmware/harbor-ui:0.4.5.2
Loaded image: vmware/harbor-log:0.4.5.2
Loaded image: vmware/harbor-db:0.4.5.2
Loaded image: vmware/harbor-jobservice:0.4.5.2
Loaded image: nginx:1.11.5
Loaded image: registry:2.5.0
Configuring Harbor...
Failed to get the IP address
```
> subsequentboot.log
```
======================= Wed Nov 16 22:57:20 UTC 2016=====================
Shutting down Harbor...
Couldn't find env file: /harbor/harbor/common/config/ui/env
======================= Wed Nov 16 23:27:46 UTC 2016=====================
Shutting down Harbor...
Couldn't find env file: /harbor/harbor/common/config/ui/env
======================= Wed Nov 16 23:38:39 UTC 2016=====================
Shutting down Harbor...
Couldn't find env file: /harbor/harbor/common/config/ui/env
======================= Wed Nov 16 23:41:24 UTC 2016=====================
Shutting down Harbor...
Couldn't find env file: /harbor/harbor/common/config/ui/env
```

**Comment by mobla** [comment]
[harbor logs.tar.gz](https://github.com/vmware/harbor/files/596286/harbor.logs.tar.gz)

**Comment by reasonerjt** [comment]
@ywk253100
The bootstrap does not have to fail if the first docker-compose down has failed, bc the containers may be not created at all in some error scenario?

**Comment by ywk253100** [comment]
This has been fixed, the bootstrap will not fail in next release.

**Comment by kamilboratynski** [comment]
@ywk253100: I am still facing similiar issue. After deploy OVA VM image and filling in static IP address space, operating system freezes during systemd boot process.
http://imgur.com/2h1PPIm

**Comment by ywk253100** [comment]
The process can not continue? If the VM can start successfully, this should not an issue.

**Comment by kamilboratynski** [comment]
@ywk253100 The process can not be continued, mainly, because systemd tries to get IP address from DHCP server and it's service has unlimited timeout. So no... VM cannot start successfully.
