### ISSUE TITLE
scrollbars on the page always visible

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1615]
all pages and all datagrids have a scrollbar and shouldn't. 
![screen shot 2017-03-15 at 4 33 53 pm](https://cloud.githubusercontent.com/assets/626032/23969534/31eda3b2-099d-11e7-85de-e9c35a0b132b.png)

**Comment by wknet123** [comment]
Has been fixed.

**Comment by lweitzman** [comment]
i'm still seeing multiple scrollbars on pages in both safari and firefox.

![safari](https://cloud.githubusercontent.com/assets/626032/24299580/0e4eca5a-1080-11e7-967a-769edfa91330.png)

**Comment by lweitzman** [comment]
there seems to be a white section at the bottom of the page
![screen shot 2017-03-24 at 10 54 12 am](https://cloud.githubusercontent.com/assets/626032/24299655/457ea392-1080-11e7-90ae-27341ab6ce8e.png)

**Comment by steven-zou** [comment]
@wknet123 

  Please apply the fix css to the mentioned pages as well. Thanks.

**Comment by steven-zou** [comment]
@lweitzman 

Fix scroll bar on sign-in page.

Checked. No white space at the bottom of user page. That's normal content area.

**Comment by lweitzman** [comment]
there is still a scrollbar in safari. notice that the vertical gray line doesn't go all the way to the bottom of the page. not sure if this is why the scroll bar is still visible on the page.
![screen shot 2017-04-03 at 8 29 20 am](https://cloud.githubusercontent.com/assets/626032/24609182/d1fb5396-1847-11e7-9951-fb2c26e9d322.png)

**Comment by steven-zou** [comment]
@lweitzman 
Disable overflow scrolling @ html body.
The scrolling of inner DIV will enable if content overflow.

**Comment by lweitzman** [comment]
not sure i understand. why is there a scroll bar visible on all pages?

**Comment by steven-zou** [comment]
@lweitzman 

  Because Clarity set height 100vh for the content area. Plus the height of header might cause height  overflow.

**Comment by steven-zou** [comment]
Verify need build changes. Will enable the fix after build scripts upgrading.
