### ISSUE TITLE
Deleting an exiting image:tagX replicated to remote registry  does not delete image:tagX from remote registry

### ISSUE THREAD

**Issue by DavidRodHub** [vmware/harbor#3618]
Have images setup to replicate from Host-A to Host-B.
Host A has several image:tags replicated successfully to Host-B
- imageA:1
- imageA:2
- imageA:3
- imageA:4 

Delete  "imageA:4" from Host-A

Note that Host-B still has all 4 image tags and remains out-of-sync with Host-A. Replication process does not remove "imageA:4" from Host-B
- imageA:1
- imageA:2
- imageA:3
- imageA:4

Is this working as designed?

Attached config and log files
----------------------------------
[harbor-host-A.tar.gz](https://github.com/vmware/harbor/files/1476875/harbor-host-A.tar.gz)
[harbor-host-B.tar.gz](https://github.com/vmware/harbor/files/1476876/harbor-host-B.tar.gz)
[harbor-logs-host-A.tar.gz](https://github.com/vmware/harbor/files/1476877/harbor-logs-host-A.tar.gz)
[harbor-logs-host-B.tar.gz](https://github.com/vmware/harbor/files/1476878/harbor-logs-host-B.tar.gz)

**Comment by ywk253100** [comment]
Seems a known issue #2238 and has been fixed.

**Comment by DavidRodHub** [comment]
Both hostA and B are on "Version v1.2.0".  Does it have the fix or do I need a new version because I still have the issue.  After replication this is what I see on HostA and B
HOSTA
 - image-A:latest
 - image-A:37
 - image-A:36

HOSTB
 - image-A:latest
 - image-A:37
 - image-A:36
 - image-A:35
 - image-A:34
 - image-A:33
 - image-A:32
 - image-A:31
 - image-A:30
 - image-A:29
 - image-A:28

**Comment by ywk253100** [comment]
1.2.0 should have the fix. 
Is there any replication job for deletion on web UI?

**Comment by DavidRodHub** [comment]
Not sure I understand "Is there any replication job for deletion on web UI".   Do I need to create a replication job to delete?

**Comment by ywk253100** [comment]
The jobs are triggered automatically to do the replication works, you can find them as described in the doc https://github.com/vmware/harbor/blob/master/docs/user_guide.md#replicating-images。
