### ISSUE TITLE
White label border color and menu item need to be fixed

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#4833]
the white label border is currently #666666 and should be #A1A1A1.
also the menu item for the white label should have the same border. currently it has none.

see https://vmware.invisionapp.com/share/2WG9HU34YVJ#/285253894_Label_Color_Specification

![Screen Shot 2018-05-01 at 9.50.30 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/8c85b5c7-79a2-4de4-84f8-6e26d4890c8b)

**Comment by steven-zou** [comment]
It should be fixed

**Comment by lweitzman** [comment]
this is still not fixed. the border around the white label should be #A1A1A1.
the border should also be on the white item in the menu.
the icon seems to be not centered.

**Comment by lweitzman** [comment]
If you don't supply a color and just supply the label you can add the new label but it has no border.

![screen shot 2018-05-30 at 8 57 06 am](https://user-images.githubusercontent.com/626032/40721442-882f276e-63e7-11e8-928c-940b016e0e2b.png)

**Comment by lweitzman** [comment]
The color menu now works on the Mac but the white color item has no border and the above  comment still is a problem.

**Comment by pengpengshui** [comment]
you mean if don't supply color , bbb and ccc should have border? if so , they will have the same appearance with choose white from color panel. my thought is that remove white form color panel, set white background color  and border as the default, or  no color no border .

**Comment by wy65701436** [comment]
@steven-zou  please help to have a look and make a decision as it's a task of sprint 35. Move it to sprint 36.

**Comment by pengpengshui** [comment]
@lweitzman

**Comment by lweitzman** [comment]
we shouldn't remove anything from the color menu. just provide a default, e.g. white, that gets selected when no color is selected. so the items should behave as if the white color was selected and have a border. every label should have a border.

**Comment by pengpengshui** [comment]
had add border when no color.

**Comment by lweitzman** [comment]
labels when no color is selected is still not working on http://10.160.25.214 even though #5118 (which is the same issue i believe) was merged.

**Comment by pengpengshui** [comment]
i[cid:image001.png@01D40236.BEDCFBF0]
I test 10.160.25.214 (click NEW LBEL, input name, click ok), the label list like above, if I misunderstand your mind?

**Comment by lweitzman** [comment]
works on https://10.193.22.115 
![screen shot 2018-06-12 at 8 28 41 am](https://user-images.githubusercontent.com/626032/41290374-b59a356c-6e1a-11e8-9c3e-726e478a6120.png)
