### ISSUE TITLE
Harbor should not display private repositories in the home page

### ISSUE THREAD

**Issue by ecirtap** [vmware/harbor#621]
Hello,

Harbor should not display private repositories in the home page, in the "Popular Repositories" Pane. Not only the name of the repository appears, but also the name of the owner, which is a potential login name to test (maliciously) elsewhere.

Unrelated: Harbor sounds very promising, thank you for your work !

**Comment by reasonerjt** [comment]
@ecirtap thanks for the suggestion, it makes sense!

**Comment by jakerobinson** [comment]
ETA on a fix for this, @reasonerjt? We have a publicly facing instance of harbor that is currently advertising these to the world after the update.

**Comment by bobbyjunzhang** [comment]
@jakerobinson We are actively looking into it now and a fix will be provided very soon. Thanks for reporting this problem - it is a major one that we want to tackle immediately.

**Comment by reasonerjt** [comment]
@jakerobinson Hopefully a fix for this will pushed to master by the end of this week.

**Comment by reasonerjt** [comment]
fixed by #627

**Comment by ecirtap** [comment]
Hello,

It is not fully fixed; private repository names are still displayed in the public home page (tested in 0.3.5). It would be wiser to not display anything about private repositories as their names can contain indications on internal (=private) entreprise activities.
